# Generated by Django 5.0.4 on 2024-05-08 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_alter_vendor_vendor_code_purchaseorder_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendor',
            old_name='on_time_delivery',
            new_name='on_time_delivery_rate',
        ),
        migrations.RenameField(
            model_name='vendorperformance',
            old_name='quality_rating',
            new_name='quality_rating_avg',
        ),
        migrations.AlterField(
            model_name='vendorperformance',
            name='average_response_time',
            field=models.FloatField(default=0),
        ),
    ]
